"""Session Durable Object — stores only userId (Privy DID) + wallet address.

Never stores the raw Privy access/identity token. Opaque session IDs are
generated by the Worker and used as Durable Object names.
"""

from __future__ import annotations

import json

from workers import DurableObject, Response


class SessionDO(DurableObject):
    """One instance per opaque session id (idFromName(session_id))."""

    def __init__(self, ctx, env):
        self.ctx = ctx
        self.env = env

    async def fetch(self, request):
        method = request.method.upper()
        if method == "GET":
            data = await self.ctx.storage.get(["userId", "walletAddress", "exp"])
            # storage.get with list returns a Map-like / dict depending on runtime
            user_id = _get(data, "userId")
            wallet = _get(data, "walletAddress")
            exp = _get(data, "exp")
            if not user_id or not wallet:
                return Response(json.dumps({"ok": False, "error": "not found"}), status=404, headers=_json_headers())
            return Response(
                json.dumps({"ok": True, "userId": user_id, "walletAddress": wallet, "exp": exp}),
                status=200,
                headers=_json_headers(),
            )
        if method == "PUT":
            try:
                body = json.loads(await request.text())
            except Exception:  # noqa: BLE001
                return Response(json.dumps({"error": "invalid JSON"}), status=400, headers=_json_headers())
            user_id = body.get("userId")
            wallet = body.get("walletAddress")
            exp = body.get("exp")
            if not isinstance(user_id, str) or not user_id:
                return Response(json.dumps({"error": "userId required"}), status=400, headers=_json_headers())
            if not isinstance(wallet, str) or not wallet.startswith("0x"):
                return Response(json.dumps({"error": "walletAddress required"}), status=400, headers=_json_headers())
            await self.ctx.storage.put(
                {
                    "userId": user_id,
                    "walletAddress": wallet,
                    "exp": int(exp) if isinstance(exp, (int, float)) else None,
                }
            )
            return Response(json.dumps({"ok": True}), status=200, headers=_json_headers())
        if method == "DELETE":
            await self.ctx.storage.delete(["userId", "walletAddress", "exp"])
            return Response(json.dumps({"ok": True}), status=200, headers=_json_headers())
        return Response(json.dumps({"error": "method not allowed"}), status=405, headers=_json_headers())


def _json_headers():
    return {"Content-Type": "application/json"}


def _get(data, key):
    if data is None:
        return None
    if isinstance(data, dict):
        return data.get(key)
    # JS Map from storage.get([...])
    try:
        return data.get(key)
    except Exception:  # noqa: BLE001
        try:
            return getattr(data, key, None)
        except Exception:  # noqa: BLE001
            return None
